apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  replicas: 3
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        #image: 825383811744.dkr.ecr.ap-northeast-2.amazonaws.com/php-apache:latest
        image: AWS_ECR_URI
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: DATE
            value: 'DATE_STRING'
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
